openapi: 3.0.0
info:
  title: Billing API
  version: v1
  description: An API for managing billing and invoices.
servers:
  - url: https://api.example.com/billing/v1
paths:
  /invoices:
    get:
      summary: List Invoices
      operationId: listInvoices
      responses:
        '200':
          description: A list of invoices.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceList'
components:
  schemas:
    Invoice:
      type: object
      properties:
        id:
          type: string
        amount:
          type: number
    InvoiceList:
      type: array
      items:
        $ref: '#/components/schemas/Invoice'